version: '3'
services:
    redis:
      container_name: plexvote_redis
      image: redis:latest
      ports:
        - 6379:6379
      volumes:
        - ./redis/config/redis.conf:/redis.conf
      command: [ "redis-server", "/redis.conf" ]
    website:
      container_name: plexvote_website
      build: ./web
      depends_on:
        - redis
      ports:
        - "80:80"
      volumes:
        - "./web:/app"